version: '3.1'

services:
  joomla:
    image: cienrxs/joomla:1.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - joomlanet
    ports:
      - 8008:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example

  joomladb:
    image: mysql:5.6
    networks:
      - joomlanet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: example

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - joomlanet
    ports:
      - 8001:80

networks:
  joomlanet:
